"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import type { Load, LoadCase, LoadCombination, LoadSource, StructuralModel, Surface } from "@linkoteq/structural-core";

type Props = { model: StructuralModel; selectedSurface?: Surface; onModelChange: (next: StructuralModel, message?: string) => void; };
type SnowWriteback = { runId: string; modelSchemaVersion: string; loadSources?: LoadSource[]; loadCases?: LoadCase[]; loads?: Load[]; warnings?: string[]; errors?: string[]; };
type ClimateRecord = { province: string; location: string; ss: number; sr: number; source?: string };

const card: React.CSSProperties = { border: "1px solid #e4e7ec", borderRadius: 8, padding: 8, background: "#fbfcfd", display: "grid", gap: 6 };
const row: React.CSSProperties = { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 5 };
const input: React.CSSProperties = { width: "100%", border: "1px solid #d0d5dd", borderRadius: 6, padding: "6px 7px", background: "white", fontSize: 11 };
const button: React.CSSProperties = { border: "1px solid #cfd6df", background: "white", borderRadius: 6, padding: "6px 8px", fontSize: 11, cursor: "pointer" };
const primary: React.CSSProperties = { ...button, background: "#17202a", color: "white", borderColor: "#17202a" };
const muted: React.CSSProperties = { fontSize: 9, color: "#667085", lineHeight: 1.4 };

function sourceStatus(model: StructuralModel, category: string) { return model.loadSources?.find(s => s.category === category)?.status || "not generated"; }
function num(v: string, fallback = 0) { const x = Number(v); return Number.isFinite(x) ? x : fallback; }
function slabGeometry(model: StructuralModel, slab?: Surface) {
  if (!slab) return { slope: 0, larger: 0, smaller: 0 };
  const pts = slab.boundaryNodeIds.map(id => model.nodes.find(node => node.id === id)?.position).filter(Boolean) as Array<{x:number;y:number;z:number}>;
  if (pts.length < 3) return { slope: 0, larger: 0, smaller: 0 };
  const xs = pts.map(p => p.x), ys = pts.map(p => p.y);
  const dx = Math.max(...xs)-Math.min(...xs), dy = Math.max(...ys)-Math.min(...ys);
  const a = {x:pts[1].x-pts[0].x,y:pts[1].y-pts[0].y,z:pts[1].z-pts[0].z}, b = {x:pts[2].x-pts[0].x,y:pts[2].y-pts[0].y,z:pts[2].z-pts[0].z};
  const nx=a.y*b.z-a.z*b.y, ny=a.z*b.x-a.x*b.z, nz=a.x*b.y-a.y*b.x;
  const slope=Math.atan2(Math.hypot(nx,ny),Math.abs(nz))*180/Math.PI;
  return { slope:Number.isFinite(slope)?slope:0, larger:Math.max(dx,dy), smaller:Math.min(dx,dy) };
}
function autoCb(larger:number,smaller:number,cw:number){
  if(!(larger>0)||!(smaller>0)||!(cw>0)) return {lc:0,cb:0.8,threshold:70};
  const l=Math.max(larger,smaller),w=Math.min(larger,smaller),lc=2*w-(w*w/l),threshold=70/(cw*cw);
  const cb=lc<=threshold?0.8:(1/cw)*(1-(1-0.8*cw)*Math.exp(-((lc*cw*cw)-70)/100));
  return {lc,cb,threshold};
}

export default function LoadManager({ model, selectedSurface, onModelChange }: Props) {
  const [open,setOpen]=useState(false),[advanced,setAdvanced]=useState(false),[busy,setBusy]=useState(false);
  const [dead,setDead]=useState("1.0"),[live,setLive]=useState("1.9"),[importance,setImportance]=useState("1.0"),[cw,setCw]=useState("1.0"),[surfaceType,setSurfaceType]=useState("normal");
  const [province,setProvince]=useState(""),[location,setLocation]=useState(""),[provinces,setProvinces]=useState<string[]>([]),[locations,setLocations]=useState<string[]>([]),[ss,setSs]=useState(""),[sr,setSr]=useState("");
  const [slopeOverride,setSlopeOverride]=useState<string|null>(null),[cbOverride,setCbOverride]=useState<string|null>(null),[message,setMessage]=useState("Select a slab to assign area loads.");

  const slab=selectedSurface?.type==="slab"?selectedSurface:undefined;
  const geometry=useMemo(()=>slabGeometry(model,slab),[model,slab]);
  const cbAuto=useMemo(()=>autoCb(geometry.larger,geometry.smaller,num(cw,1)),[geometry,cw]);
  const slope=slopeOverride===null?geometry.slope:num(slopeOverride,geometry.slope),cb=cbOverride===null?cbAuto.cb:num(cbOverride,cbAuto.cb);
  const loadsForSlab=useMemo(()=>slab?model.loads.filter(l=>l.targetId===slab.id):[],[model.loads,slab]);

  useEffect(()=>{fetch("/api/calculators/snow/climate").then(r=>r.json()).then(d=>setProvinces(Array.isArray(d.provinces)?d.provinces:[])).catch(()=>setMessage("Could not load Snow Calculator locations."));},[]);
  useEffect(()=>{setLocation("");setLocations([]);if(!province)return;fetch(`/api/calculators/snow/climate?province=${encodeURIComponent(province)}`).then(r=>r.json()).then(d=>setLocations(Array.isArray(d.locations)?d.locations:[])).catch(()=>setMessage("Could not load locations."));},[province]);
  useEffect(()=>{if(!province||!location)return;fetch(`/api/calculators/snow/climate?province=${encodeURIComponent(province)}&location=${encodeURIComponent(location)}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d?.detail||d?.error||"Climate lookup failed");return d as ClimateRecord;}).then(d=>{setSs(String(d.ss));setSr(String(d.sr));setMessage(`${d.location}, ${d.province}: Ss ${d.ss} kPa · Sr ${d.sr} kPa loaded.`);}).catch(e=>setMessage(e instanceof Error?e.message:"Climate lookup failed."));},[province,location]);

  function withSource(next:StructuralModel,source:LoadSource){return {...next,schemaVersion:"0.2" as const,loadSources:[...(next.loadSources||[]).filter(s=>s.id!==source.id),source]};}
  function assignManual(category:"dead"|"live",valueText:string){if(!slab)return setMessage("Select a slab first.");const magnitude=Number(valueText);if(!Number.isFinite(magnitude)||magnitude<0)return setMessage("Load must be a non-negative number.");const sourceId=`SRC-${category.toUpperCase()}`,caseId=category==="dead"?"D":"L";const source:LoadSource={id:sourceId,category,name:`${category==="dead"?"Dead":"Live"} Load`,calculator:"manual",status:"manual",generatedAt:new Date().toISOString(),summary:{areaLoadKPa:magnitude}};const loadCase:LoadCase={id:caseId,name:category==="dead"?"Dead":"Live",category,sourceId,analysisType:"static"};const load:Load={id:`${caseId}-${slab.id}`,type:"area",targetId:slab.id,targetType:"surface",loadCaseId:caseId,direction:{x:0,y:0,z:-1},magnitude,unit:"kPa",provenance:{sourceId,note:"Manual area load assigned in Linkoteq Load Manager"}};let next:StructuralModel={...model,schemaVersion:"0.2",loadCases:[...model.loadCases.filter(c=>c.id!==caseId),loadCase],loads:[...model.loads.filter(l=>l.id!==load.id),load]};next=withSource(next,source);onModelChange(next,`${loadCase.name} load assigned to ${slab.id}.`);}
  function setTransfer(method:"one-way"|"two-way"|"shell"|"manual"){if(!slab)return;onModelChange({...model,schemaVersion:"0.2",surfaces:model.surfaces.map(s=>s.id===slab.id?{...s,loadTransfer:{...(s.loadTransfer||{}),method}}:s)},`${slab.id} load transfer = ${method}.`);}
  async function runSnow(){if(!slab)return setMessage("Select a slab first.");if(!province||!location)return setMessage("Choose Province / Territory and Location first.");if(!ss||!sr)return setMessage("Climate data has not loaded yet.");setBusy(true);setMessage("Running NBCC 2020 Snow Calculator…");const runId=`snow-${Date.now()}`;const payload={modelSchemaVersion:"0.2",projectId:model.project.id,runId,calculator:"snow",targetIds:[slab.id],inputs:{target_surface_id:slab.id,mode:"UNIFORM_ROOF",jurisdiction:model.project.jurisdiction||`${location}, ${province}`,common:{ss:num(ss),sr_climatic:num(sr),roof_slope_alpha:slope,roof_surface_type:surfaceType,is:num(importance,1),cw:num(cw,1),cb,adjacent_surface_drift_applicable:false},geometry_context:{larger_plan_dimension_m:geometry.larger,smaller_plan_dimension_m:geometry.smaller,characteristic_length_m:cbAuto.lc,auto_cb:cbAuto.cb,auto_slope_deg:geometry.slope,province,location},lower_roof_cases:[],distribution_points:8}};try{const response=await fetch("/api/calculators/snow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data?.error||data?.detail||`Snow service returned ${response.status}`);const writeback=data as SnowWriteback;if(writeback.errors?.length)throw new Error(writeback.errors.join("; "));const ids=new Set((writeback.loadSources||[]).map(s=>s.id)),caseIds=new Set((writeback.loadCases||[]).map(c=>c.id)),loadIds=new Set((writeback.loads||[]).map(l=>l.id));onModelChange({...model,schemaVersion:"0.2",loadSources:[...(model.loadSources||[]).filter(s=>!ids.has(s.id)),...(writeback.loadSources||[])],loadCases:[...model.loadCases.filter(c=>!caseIds.has(c.id)),...(writeback.loadCases||[])],loads:[...model.loads.filter(l=>!loadIds.has(l.id)),...(writeback.loads||[])]},`Snow load generated for ${slab.id}.`);setMessage(writeback.warnings?.length?`Snow generated with warning: ${writeback.warnings.join("; ")}`:`Snow generated and assigned to ${slab.id}.`);}catch(e){setMessage(e instanceof Error?e.message:"Snow calculation failed.");}finally{setBusy(false);}}
  function addDraftCombinations(){const combos:LoadCombination[]=[{id:"ULS-USER-1",name:"ULS draft: 1.25D + 1.5L + 1.0S",limitState:"ULS",factors:{D:1.25,L:1.5,S:1},codeRef:"Draft template — engineer must verify governing NBCC 2020 combination"},{id:"SLS-USER-1",name:"SLS draft: 1.0D + 1.0L + 1.0S",limitState:"SLS",factors:{D:1,L:1,S:1},codeRef:"Draft template — engineer must verify governing NBCC 2020 combination"}];onModelChange({...model,schemaVersion:"0.2",loadCombinations:[...model.loadCombinations.filter(c=>!combos.some(x=>x.id===c.id)),...combos]},"Draft load combinations added for review.");}

  const content=<div style={{display:"grid",gap:8}}>
    <div style={card}><strong style={{fontSize:12}}>Load Manager · Core v0.2</strong><div style={muted}>Target: {slab?`${slab.id} · ${slab.levelId||"no level"}`:"select a slab"}</div>{slab&&<label style={{fontSize:10}}>Slab load transfer<select style={input} value={slab.loadTransfer?.method||"two-way"} onChange={e=>setTransfer(e.target.value as "one-way"|"two-way"|"shell"|"manual")}><option value="one-way">One-way</option><option value="two-way">Two-way</option><option value="shell">Shell</option><option value="manual">Manual</option></select></label>}</div>
    <div style={card}><strong style={{fontSize:11}}>Load Sources</strong>{(["dead","live","snow","wind","seismic"] as const).map(c=><div key={c} style={{display:"flex",justifyContent:"space-between",fontSize:10}}><span>{c[0].toUpperCase()+c.slice(1)}</span><span style={{color:sourceStatus(model,c)==="not generated"?"#98a2b3":"#027a48"}}>{sourceStatus(model,c)}</span></div>)}</div>
    <div style={card}><strong style={{fontSize:11}}>Dead / Live area loads</strong><div style={row}><label style={{fontSize:9}}>Dead kPa<input style={input} value={dead} onChange={e=>setDead(e.target.value)}/></label><label style={{fontSize:9}}>Live kPa<input style={input} value={live} onChange={e=>setLive(e.target.value)}/></label></div><div style={row}><button style={button} onClick={()=>assignManual("dead",dead)}>Assign Dead</button><button style={button} onClick={()=>assignManual("live",live)}>Assign Live</button></div></div>
    <div style={card}><strong style={{fontSize:11}}>Snow · NBCC 2020</strong><div style={muted}>Only location and Importance Factor are required. Geometry values come from the selected slab.</div><label style={{fontSize:9}}>Province / Territory<select style={input} value={province} onChange={e=>setProvince(e.target.value)}><option value="">Select province</option>{provinces.map(p=><option key={p}>{p}</option>)}</select></label><label style={{fontSize:9}}>Location<select style={input} value={location} disabled={!province} onChange={e=>setLocation(e.target.value)}><option value="">{province?"Select location":"Select province first"}</option>{locations.map(l=><option key={l}>{l}</option>)}</select></label><label style={{fontSize:9}}>Importance factor, Is<input style={input} value={importance} onChange={e=>setImportance(e.target.value)}/></label><div style={{padding:"6px 7px",borderRadius:6,background:"#f2f4f7",fontSize:9,lineHeight:1.5}}><b>Auto from model</b><br/>Roof: {geometry.larger.toFixed(2)} × {geometry.smaller.toFixed(2)} m · slope {geometry.slope.toFixed(2)}° · Cb {cbAuto.cb.toFixed(3)}{location&&<> · Ss {ss||"…"} · Sr {sr||"…"} kPa</>}</div><button style={button} onClick={()=>setAdvanced(v=>!v)}>{advanced?"Hide":"Review / edit"} auto parameters</button>{advanced&&<div style={{...card,background:"white"}}><div style={muted}>Automatic/default values. Edit only when project conditions require it.</div><div style={row}><label style={{fontSize:9}}>Ss kPa<input style={input} value={ss} onChange={e=>setSs(e.target.value)}/></label><label style={{fontSize:9}}>Sr kPa<input style={input} value={sr} onChange={e=>setSr(e.target.value)}/></label></div><div style={row}><label style={{fontSize:9}}>Slope °<input style={input} value={slopeOverride??geometry.slope.toFixed(3)} onChange={e=>setSlopeOverride(e.target.value)}/><button style={button} onClick={()=>setSlopeOverride(null)}>Use model</button></label><label style={{fontSize:9}}>Roof surface<select style={input} value={surfaceType} onChange={e=>setSurfaceType(e.target.value)}><option value="normal">Normal</option><option value="smooth_slippery">Smooth / slippery</option></select></label></div><div style={row}><label style={{fontSize:9}}>Cw<input style={input} value={cw} onChange={e=>setCw(e.target.value)}/><span style={muted}>Default 1.0; review exposure.</span></label><label style={{fontSize:9}}>Cb<input style={input} value={cbOverride??cbAuto.cb.toFixed(4)} onChange={e=>setCbOverride(e.target.value)}/><button style={button} onClick={()=>setCbOverride(null)}>Use model</button></label></div><div style={muted}>l={geometry.larger.toFixed(3)} m · w={geometry.smaller.toFixed(3)} m · lc={cbAuto.lc.toFixed(3)} m · 70/Cw²={cbAuto.threshold.toFixed(3)} m</div></div>}<button style={primary} disabled={!slab||busy||!province||!location} onClick={runSnow}>{busy?"Calculating…":"Run Snow → selected slab"}</button></div>
    <div style={card}><strong style={{fontSize:11}}>Load Cases</strong>{model.loadCases.length?model.loadCases.map(c=><div key={c.id} style={{fontSize:10}}>{c.id} · {c.name} <span style={{color:"#667085"}}>({c.category})</span></div>):<span style={{fontSize:10,color:"#98a2b3"}}>No load cases yet.</span>}</div>
    <div style={card}><strong style={{fontSize:11}}>Combinations</strong>{model.loadCombinations.map(c=><div key={c.id} style={{fontSize:9}}>{c.name}</div>)}<button style={button} onClick={addDraftCombinations}>Add draft NBCC review set</button><small style={{fontSize:8,color:"#b54708"}}>Draft combinations are not certified code selection. Engineer review is required.</small></div>
    {slab&&<div style={card}><strong style={{fontSize:11}}>Loads on {slab.id}</strong>{loadsForSlab.length?loadsForSlab.map(l=><div key={l.id} style={{fontSize:10}}>{l.loadCaseId}: {l.magnitude} {l.unit} · {l.type}</div>):<span style={{fontSize:10,color:"#98a2b3"}}>No loads assigned.</span>}</div>}<div style={muted}>{message}</div>
  </div>;

  return <><div className="loadManagerEmbedded">{content}</div>{typeof document!=="undefined"&&createPortal(<><button className="loadManagerLauncher" onClick={()=>setOpen(true)} aria-label="Open Load Manager">Loads</button>{open&&<div className="loadManagerBackdrop" onPointerDown={()=>setOpen(false)}><aside className="loadManagerDrawer" onPointerDown={e=>e.stopPropagation()}><div className="loadManagerDrawerHeader"><div><strong>Load Manager</strong><span>{slab?` · ${slab.id}`:" · no slab selected"}</span></div><button onClick={()=>setOpen(false)} aria-label="Close Load Manager">×</button></div><div className="loadManagerDrawerBody">{content}</div></aside></div>}</>,document.body)}</>;
}
