"use client";

import { Canvas, ThreeEvent, useThree } from "@react-three/fiber";
import { Grid, Html, OrbitControls } from "@react-three/drei";
import * as THREE from "three";
import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import type { GridLine, Member, Node, Section, StructuralModel, Surface } from "@linkoteq/structural-core";
import LoadManager from "./LoadManager";

type Tool = "select" | "beam" | "column" | "brace" | "wall" | "slab";
type GridAxis = "X" | "Y";
type EntityRef = { type: "member" | "surface"; id: string };
type ContextMenuState = { x: number; y: number; kind: "entity"; entity: EntityRef } | { x: number; y: number; kind: "node"; nodeId: string } | null;
type SectionOption = { id: string; designation: string; designation_metric?: string | null; family: string; properties: Record<string, number | string | null> };
type ClipboardModel = { entities: EntityRef[]; members: Member[]; surfaces: Surface[]; nodes: Node[]; basePoint: { x: number; y: number; z: number } } | null;
type LtqPackage = { format: "linkoteq-project"; version: 1; savedAt: string; model: StructuralModel };

const initialX = [0, 6, 12];
const initialY = [0, 4, 8];
const initialLevels = [{ id: "L0", name: "Ground", elevation: 0 }, { id: "L1", name: "Level 1", elevation: 3.5 }];
const clone = <T,>(v: T): T => JSON.parse(JSON.stringify(v));
const key = (x: number, y: number, z: number) => `${x.toFixed(5)}|${y.toFixed(5)}|${z.toFixed(5)}`;
const vec = (n: Node) => new THREE.Vector3(n.position.x, n.position.z, n.position.y);
const sortedUnique = (a: number[]) => [...new Set(a.map(v => +v.toFixed(5)))].sort((x, y) => x - y);

function makeGridLines(xs: number[], ys: number[], xLabels?: string[], yLabels?: string[]): GridLine[] {
  const minX = Math.min(...xs) - 1, maxX = Math.max(...xs) + 1, minY = Math.min(...ys) - 1, maxY = Math.max(...ys) + 1;
  return [
    ...xs.map((x, i) => ({ id: `GX${i + 1}`, label: xLabels?.[i] || String.fromCharCode(65 + i), start: { x, y: minY, z: 0 }, end: { x, y: maxY, z: 0 } })),
    ...ys.map((y, i) => ({ id: `GY${i + 1}`, label: yLabels?.[i] || `${i + 1}`, start: { x: minX, y, z: 0 }, end: { x: maxX, y, z: 0 } }))
  ];
}
function extractGrid(grids: GridLine[]) {
  const xg = grids.filter(g => Math.abs(g.start.x - g.end.x) < 1e-6).sort((a,b)=>a.start.x-b.start.x);
  const yg = grids.filter(g => Math.abs(g.start.y - g.end.y) < 1e-6).sort((a,b)=>a.start.y-b.start.y);
  return { xs: sortedUnique(xg.map(g=>g.start.x)), ys: sortedUnique(yg.map(g=>g.start.y)), xg, yg };
}
function makeNodes(xs:number[], ys:number[], levels:StructuralModel["levels"]):Node[]{
  let i=1; const out:Node[]=[]; for(const l of levels) for(const y of ys) for(const x of xs) out.push({id:`N${i++}`,position:{x,y,z:l.elevation},levelId:l.id}); return out;
}
function findNode(nodes:Node[],x:number,y:number,z:number){const k=key(x,y,z);return nodes.find(n=>key(n.position.x,n.position.y,n.position.z)===k);}
function createBaseModel():StructuralModel{
  const nodes=makeNodes(initialX,initialY,initialLevels);
  const a=findNode(nodes,0,0,0)!,b=findNode(nodes,6,0,0)!,c=findNode(nodes,0,0,3.5)!,d=findNode(nodes,6,0,3.5)!;
  return {schemaVersion:"0.2",project:{id:"P001",name:"3D Model Prototype",units:"SI"},levels:clone(initialLevels),grids:makeGridLines(initialX,initialY),nodes,members:[{id:"C1",type:"column",startNodeId:a.id,endNodeId:c.id},{id:"C2",type:"column",startNodeId:b.id,endNodeId:d.id},{id:"B1",type:"beam",startNodeId:c.id,endNodeId:d.id,levelId:"L1"}],surfaces:[],diaphragms:[],materials:[],sections:[],supports:[],loadSources:[],loadCases:[],loads:[],loadCombinations:[]};
}
const baseModel=createBaseModel();

function MemberMesh({member,nodes,selected,onClick,onContext}:{member:Member;nodes:Node[];selected:boolean;onClick:(m:Member,e:ThreeEvent<MouseEvent>)=>void;onContext:(m:Member,e:ThreeEvent<MouseEvent>)=>void}){
  const a=nodes.find(n=>n.id===member.startNodeId),b=nodes.find(n=>n.id===member.endNodeId);
  const geometry=useMemo(()=>{if(!a||!b)return null;const p=vec(a),q=vec(b),dir=q.clone().sub(p),len=dir.length();if(!len)return null;const g=new THREE.BoxGeometry(selected?.28:.22,len,selected?.28:.22);g.translate(0,len/2,0);g.applyQuaternion(new THREE.Quaternion().setFromUnitVectors(new THREE.Vector3(0,1,0),dir.normalize()));g.translate(p.x,p.y,p.z);return g;},[a,b,selected]);
  if(!geometry)return null; const color=member.type==="column"?"#2367a8":member.type==="brace"?"#d97706":"#26734d";
  return <mesh geometry={geometry} onClick={e=>{e.stopPropagation();onClick(member,e);}} onContextMenu={e=>{e.stopPropagation();e.nativeEvent.preventDefault();onContext(member,e);}} castShadow><meshStandardMaterial color={selected?"#f97316":color}/></mesh>;
}
function SurfaceMesh({surface,nodes,levels,selected,onClick,onContext}:{surface:Surface;nodes:Node[];levels:StructuralModel["levels"];selected:boolean;onClick:(s:Surface,e:ThreeEvent<MouseEvent>)=>void;onContext:(s:Surface,e:ThreeEvent<MouseEvent>)=>void}){
  const pts=surface.boundaryNodeIds.map(id=>nodes.find(n=>n.id===id)).filter(Boolean) as Node[];
  const handlers={onClick:(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();onClick(surface,e);},onContextMenu:(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();e.nativeEvent.preventDefault();onContext(surface,e);}};
  if(surface.type==="slab"&&pts.length>=3){const o=pts[0];const shape=new THREE.Shape();shape.moveTo(0,0);for(let i=1;i<pts.length;i++)shape.lineTo(pts[i].position.x-o.position.x,pts[i].position.y-o.position.y);shape.closePath();const geo=new THREE.ShapeGeometry(shape);geo.rotateX(-Math.PI/2);return <mesh {...handlers} geometry={geo} position={[o.position.x,o.position.z+.015,o.position.y]}><meshStandardMaterial color={selected?"#f97316":"#9ca3af"} transparent opacity={.48} side={THREE.DoubleSide}/></mesh>;}
  if(surface.type==="wall"&&pts.length>=2){const [a,b]=pts;const levelsSorted=[...levels].sort((x,y)=>x.elevation-y.elevation);const li=levelsSorted.findIndex(l=>l.id===surface.levelId);const h=li>=0&&levelsSorted[li+1]?levelsSorted[li+1].elevation-levelsSorted[li].elevation:3.5;const len=Math.hypot(b.position.x-a.position.x,b.position.y-a.position.y),ang=Math.atan2(b.position.y-a.position.y,b.position.x-a.position.x);return <mesh {...handlers} position={[(a.position.x+b.position.x)/2,a.position.z+h/2,(a.position.y+b.position.y)/2]} rotation={[0,-ang,0]}><boxGeometry args={[len,h,.15]}/><meshStandardMaterial color={selected?"#f97316":"#8b5e3c"} transparent opacity={.65}/></mesh>;}
  return null;
}
function NodePoint({node,selected,onClick,onContext,showLabel}:{node:Node;selected:boolean;onClick:(n:Node,e:ThreeEvent<MouseEvent>)=>void;onContext:(n:Node,e:ThreeEvent<MouseEvent>)=>void;showLabel:boolean}){
  return <group position={vec(node)}><mesh onClick={e=>{e.stopPropagation();onClick(node,e);}} onContextMenu={e=>{e.stopPropagation();e.nativeEvent.preventDefault();onContext(node,e);}}><sphereGeometry args={[selected?.15:.095,16,16]}/><meshStandardMaterial color={selected?"#f97316":"#2563eb"}/></mesh>{showLabel&&<Html position={[0,.2,0]} center><span className="nodeLabel">{node.id}</span></Html>}</group>;
}
function ModelGrid({grid,elevation,showLabel}:{grid:GridLine;elevation:number;showLabel:boolean}){
  const geometry=useMemo(()=>new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(grid.start.x,elevation+.012,grid.start.y),new THREE.Vector3(grid.end.x,elevation+.012,grid.end.y)]),[grid.start.x,grid.start.y,grid.end.x,grid.end.y,elevation]);
  const isX=Math.abs(grid.start.x-grid.end.x)<1e-6;const lp:[number,number,number]=isX?[grid.start.x,elevation+.03,grid.start.y-.45]:[grid.start.x-.45,elevation+.03,grid.start.y];
  return <><lineSegments geometry={geometry}><lineBasicMaterial color="#64748b" transparent opacity={.78}/></lineSegments>{showLabel&&<Html position={lp} center><span className="gridLabel">{grid.label}</span></Html>}</>;
}
function Dimensions({model,onGrid,onLevel}:{model:StructuralModel;onGrid:(a:GridAxis,i:number,v:number)=>void;onLevel:(i:number,v:number)=>void}){
  const {xs,ys}=extractGrid(model.grids),levels=[...model.levels].sort((a,b)=>a.elevation-b.elevation),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys);const out:React.ReactNode[]=[];
  xs.slice(0,-1).forEach((x,i)=>{const d=xs[i+1]-x;out.push(<Html key={`x${i}`} position={[(x+xs[i+1])/2,.04,minY-.9]} center><button className="dimLabel" onClick={()=>onGrid("X",i,d)}>{d.toFixed(2)} m</button></Html>);});
  ys.slice(0,-1).forEach((y,i)=>{const d=ys[i+1]-y;out.push(<Html key={`y${i}`} position={[minX-.9,.04,(y+ys[i+1])/2]} center><button className="dimLabel" onClick={()=>onGrid("Y",i,d)}>{d.toFixed(2)} m</button></Html>);});
  levels.slice(0,-1).forEach((l,i)=>{const d=levels[i+1].elevation-l.elevation;out.push(<Html key={`l${i}`} position={[maxX+1.1,(l.elevation+levels[i+1].elevation)/2,minY]} center><button className="dimLabel" onClick={()=>onLevel(i,d)}>{d.toFixed(2)} m</button></Html>);});
  return <>{out}</>;
}
function CameraRig({model,resetSignal}:{model:StructuralModel;resetSignal:number}){
  const {camera,size}=useThree();const last=useRef(-1);
  useEffect(()=>{if(last.current===resetSignal)return;last.current=resetSignal;const xs=model.nodes.map(n=>n.position.x),ys=model.nodes.map(n=>n.position.y),zs=model.nodes.map(n=>n.position.z);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),minZ=Math.min(...zs),maxZ=Math.max(...zs),cx=(minX+maxX)/2,cy=(minY+maxY)/2,cz=(minZ+maxZ)/2,span=Math.max(maxX-minX,maxY-minY,maxZ-minZ,6),mobile=size.width<720,dist=span*(mobile?2.25:1.45);camera.position.set(cx+dist,cz+dist*.72,cy+dist);camera.lookAt(cx,cz,cy);camera.updateProjectionMatrix();},[camera,model,resetSignal,size.width]);return null;
}
function Scene(props:{model:StructuralModel;selected:EntityRef[];selectedNodes:string[];onEntityClick:(e:EntityRef,ev:ThreeEvent<MouseEvent>)=>void;onEntityContext:(e:EntityRef,ev:ThreeEvent<MouseEvent>)=>void;onNodeClick:(n:Node,ev:ThreeEvent<MouseEvent>)=>void;onNodeContext:(n:Node,ev:ThreeEvent<MouseEvent>)=>void;onGrid:(a:GridAxis,i:number,v:number)=>void;onLevel:(i:number,v:number)=>void;resetSignal:number}){
  const {width}=useThree(s=>s.size),compact=width<720,ground=[...props.model.levels].sort((a,b)=>a.elevation-b.elevation)[0];
  const {xs,ys}=extractGrid(props.model.grids);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),cx=(minX+maxX)/2,cy=(minY+maxY)/2,gridW=Math.max(maxX-minX+4,12),gridD=Math.max(maxY-minY+4,12);
  return <><CameraRig model={props.model} resetSignal={props.resetSignal}/><color attach="background" args={["#eef3f8"]}/><ambientLight intensity={1.1}/><directionalLight position={[10,14,8]} intensity={1.8}/>{props.model.grids.map(g=><ModelGrid key={g.id} grid={g} elevation={ground?.elevation||0} showLabel={!compact}/>)}{!compact&&props.model.levels.filter(l=>l.id!==ground?.id).map(l=>props.model.grids.map(g=><ModelGrid key={`${l.id}-${g.id}`} grid={g} elevation={l.elevation} showLabel={false}/>))}{!compact&&<Dimensions model={props.model} onGrid={props.onGrid} onLevel={props.onLevel}/>} {props.model.nodes.filter(n=>!compact||n.levelId===ground?.id||props.selectedNodes.includes(n.id)).map(n=><NodePoint key={n.id} node={n} selected={props.selectedNodes.includes(n.id)} showLabel={!compact} onClick={props.onNodeClick} onContext={props.onNodeContext}/>)}{props.model.members.map(m=><MemberMesh key={m.id} member={m} nodes={props.model.nodes} selected={props.selected.some(s=>s.type==="member"&&s.id===m.id)} onClick={(mm,e)=>props.onEntityClick({type:"member",id:mm.id},e)} onContext={(mm,e)=>props.onEntityContext({type:"member",id:mm.id},e)}/>)}{props.model.surfaces.map(s=><SurfaceMesh key={s.id} surface={s} nodes={props.model.nodes} levels={props.model.levels} selected={props.selected.some(x=>x.type==="surface"&&x.id===s.id)} onClick={(ss,e)=>props.onEntityClick({type:"surface",id:ss.id},e)} onContext={(ss,e)=>props.onEntityContext({type:"surface",id:ss.id},e)}/>)}<Grid position={[cx,-.02,cy]} args={[gridW,gridD]} cellSize={1} sectionSize={5} fadeDistance={compact?32:45}/><OrbitControls makeDefault enableZoom enablePan target={[cx,1.75,cy]} minDistance={2} maxDistance={100}/></>;
}

export default function StructuralEditor(){
  const [model,setModel]=useState<StructuralModel>(baseModel),[tool,setTool]=useState<Tool>("select"),[selected,setSelected]=useState<EntityRef[]>([]),[selectedNodes,setSelectedNodes]=useState<string[]>([]),[status,setStatus]=useState("Ready"),[past,setPast]=useState<StructuralModel[]>([]),[future,setFuture]=useState<StructuralModel[]>([]),[context,setContext]=useState<ContextMenuState>(null),[clipboard,setClipboard]=useState<ClipboardModel>(null),[basePointId,setBasePointId]=useState<string|null>(null),[awaitingBase,setAwaitingBase]=useState(false),[resetSignal,setResetSignal]=useState(0);
  const [gridAxis,setGridAxis]=useState<GridAxis>("X"),[gridName,setGridName]=useState("D"),[gridCoordinate,setGridCoordinate]=useState("18"),[levelName,setLevelName]=useState("Level 2"),[levelElevation,setLevelElevation]=useState("7"),[sectionOptions,setSectionOptions]=useState<SectionOption[]>([]);
  const projectInput=useRef<HTMLInputElement>(null),aiInput=useRef<HTMLInputElement>(null),dxfInput=useRef<HTMLInputElement>(null),ifcInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{fetch("/api/w-sections").then(r=>r.json()).then(d=>setSectionOptions(Array.isArray(d.sections)?d.sections:[])).catch(()=>{});},[]);
  const commit=(next:StructuralModel,msg?:string)=>{setPast(p=>[...p.slice(-49),clone(model)]);setFuture([]);setModel(next);if(msg)setStatus(msg);};
  const undo=()=>{if(!past.length)return;const p=past[past.length-1];setFuture(f=>[clone(model),...f]);setPast(x=>x.slice(0,-1));setModel(p);setSelected([]);};
  const redo=()=>{if(!future.length)return;const n=future[0];setPast(p=>[...p,clone(model)]);setFuture(f=>f.slice(1));setModel(n);setSelected([]);};
  const isSelected=(r:EntityRef)=>selected.some(x=>x.type===r.type&&x.id===r.id);
  function selectEntity(ref:EntityRef,ev?:ThreeEvent<MouseEvent>){const multi=!!(ev?.nativeEvent.ctrlKey||ev?.nativeEvent.metaKey);let next:EntityRef[];if(multi){next=isSelected(ref)?selected.filter(x=>!(x.type===ref.type&&x.id===ref.id)):[...selected,ref];}else next=[ref];setSelected(next);setSelectedNodes([]);setTool("select");if(next.length>1&&!basePointId){setAwaitingBase(true);setStatus(`${next.length} elements selected — click a node to set base point.`);}else setStatus(`${next.length} element(s) selected.`);}
  function entityNodeIds(refs:EntityRef[]){const ids=new Set<string>();for(const r of refs){if(r.type==="member"){const m=model.members.find(x=>x.id===r.id);if(m){ids.add(m.startNodeId);ids.add(m.endNodeId);}}else{const s=model.surfaces.find(x=>x.id===r.id);s?.boundaryNodeIds.forEach(id=>ids.add(id));}}return [...ids];}
  function chooseBasePoint(node:Node){setBasePointId(node.id);setAwaitingBase(false);setSelectedNodes([node.id]);setStatus(`Base point = ${node.id}. Copy is ready.`);}
  function onNodeClick(node:Node,ev:ThreeEvent<MouseEvent>){if(awaitingBase){chooseBasePoint(node);return;}if(tool==="select"){setSelected([]);setSelectedNodes([node.id]);setStatus(`Node ${node.id} selected.`);return;}const ids=selectedNodes.includes(node.id)?selectedNodes:[...selectedNodes,node.id];setSelectedNodes(ids);const ns=ids.map(id=>model.nodes.find(n=>n.id===id)).filter(Boolean) as Node[];if(tool==="slab"){if(ns.length===3){setStatus("3 points selected — press Enter/Finish for triangle or click 4th point.");return;}if(ns.length>=4){finishSlab(ids.slice(0,4));return;}return;}if(ns.length<2)return;const [a,b]=ns;if(tool==="beam"&&a.levelId!==b.levelId)return setStatus("Beam nodes must be on same level.");if(tool==="column"&&(Math.abs(a.position.x-b.position.x)>1e-6||Math.abs(a.position.y-b.position.y)>1e-6||a.levelId===b.levelId))return setStatus("Column nodes must be vertically aligned.");if(tool==="wall"&&a.levelId!==b.levelId)return setStatus("Wall nodes must be on same level.");if(tool==="wall"){commit({...model,surfaces:[...model.surfaces,{id:`W${model.surfaces.filter(s=>s.type==="wall").length+1}`,type:"wall",boundaryNodeIds:[a.id,b.id],levelId:a.levelId,thickness:.15}]},"Wall created.");}else{const prefix=tool==="beam"?"B":tool==="column"?"C":"BR";const m:Member={id:`${prefix}${model.members.filter(x=>x.type===tool).length+1}`,type:tool as Member["type"],startNodeId:a.id,endNodeId:b.id,levelId:tool==="beam"?a.levelId:undefined};commit({...model,members:[...model.members,m]},`${tool} created.`);}setSelectedNodes([]);}
  function finishSlab(ids=selectedNodes){if(ids.length<3)return;const ns=ids.map(id=>model.nodes.find(n=>n.id===id)).filter(Boolean) as Node[];if(!ns.every(n=>n.levelId===ns[0].levelId))return setStatus("Slab points must be on same level.");commit({...model,surfaces:[...model.surfaces,{id:`S${model.surfaces.filter(s=>s.type==="slab").length+1}`,type:"slab",boundaryNodeIds:ids.slice(0,4),levelId:ns[0].levelId,thickness:.18,loadTransfer:{method:"two-way"}}]},`${Math.min(ids.length,4)}-point slab created.`);setSelectedNodes([]);}
  function copySelection(){if(!selected.length)return setStatus("Select element(s) first.");let bp=model.nodes.find(n=>n.id===basePointId);if(selected.length>1&&!bp){setAwaitingBase(true);setStatus("Choose a base point node before copying multiple elements.");return;}const ids=entityNodeIds(selected),nodes=model.nodes.filter(n=>ids.includes(n.id));if(!bp)bp=nodes[0];if(!bp)return;setClipboard({entities:clone(selected),members:clone(model.members.filter(m=>selected.some(s=>s.type==="member"&&s.id===m.id))),surfaces:clone(model.surfaces.filter(s=>selected.some(x=>x.type==="surface"&&x.id===s.id))),nodes:clone(nodes),basePoint:clone(bp.position)});setStatus(`${selected.length} element(s) copied. Right-click a target node and Paste Here.`);}
  function pasteAt(target:Node){if(!clipboard)return setStatus("Nothing copied.");const dx=target.position.x-clipboard.basePoint.x,dy=target.position.y-clipboard.basePoint.y,dz=target.position.z-clipboard.basePoint.z;const next=clone(model);const nodeMap=new Map<string,string>();let nodeCounter=next.nodes.length+1,levelCounter=next.levels.length;for(const src of clipboard.nodes){const x=src.position.x+dx,y=src.position.y+dy,z=src.position.z+dz;let existing=findNode(next.nodes,x,y,z);let level=next.levels.find(l=>Math.abs(l.elevation-z)<1e-6);if(!level){level={id:`L${levelCounter++}`,name:`Level ${z.toFixed(2)}m`,elevation:z};next.levels.push(level);}if(!existing){existing={id:`N${nodeCounter++}`,position:{x,y,z},levelId:level.id};next.nodes.push(existing);}nodeMap.set(src.id,existing.id);}const newRefs:EntityRef[]=[];for(const src of clipboard.members){const p=src.type==="beam"?"B":src.type==="column"?"C":"BR",id=`${p}${next.members.filter(m=>m.type===src.type).length+1}`,startNodeId=nodeMap.get(src.startNodeId)!,endNodeId=nodeMap.get(src.endNodeId)!;const start=next.nodes.find(n=>n.id===startNodeId)!;const m:Member={...clone(src),id,startNodeId,endNodeId,levelId:src.type==="beam"?start.levelId:src.levelId};next.members.push(m);newRefs.push({type:"member",id});}for(const src of clipboard.surfaces){const p=src.type==="slab"?"S":"W",id=`${p}${next.surfaces.filter(s=>s.type===src.type).length+1}`,boundaryNodeIds=src.boundaryNodeIds.map(n=>nodeMap.get(n)!),first=next.nodes.find(n=>n.id===boundaryNodeIds[0])!;next.surfaces.push({...clone(src),id,boundaryNodeIds,levelId:first.levelId});newRefs.push({type:"surface",id});}next.levels.sort((a,b)=>a.elevation-b.elevation);commit(next,`Pasted ${newRefs.length} element(s) at ${target.id}. Missing nodes/levels were created.`);setSelected(newRefs);setSelectedNodes([]);setContext(null);setResetSignal(r=>r+1);}
  function deleteSelection(){if(!selected.length)return;const ids=new Set(selected.map(s=>s.id));commit({...model,members:model.members.filter(m=>!ids.has(m.id)),surfaces:model.surfaces.filter(s=>!ids.has(s.id)),loads:model.loads.filter(l=>!ids.has(l.targetId))},`${selected.length} element(s) deleted.`);setSelected([]);}
  function addGrid(){const c=Number(gridCoordinate);if(!Number.isFinite(c))return;const {xs,ys,xg,yg}=extractGrid(model.grids);const nx=gridAxis==="X"?sortedUnique([...xs,c]):xs,ny=gridAxis==="Y"?sortedUnique([...ys,c]):ys;const xl=nx.map(x=>gridAxis==="X"&&Math.abs(x-c)<1e-6?gridName:(xg.find(g=>Math.abs(g.start.x-x)<1e-6)?.label||`X${nx.indexOf(x)+1}`)),yl=ny.map(y=>gridAxis==="Y"&&Math.abs(y-c)<1e-6?gridName:(yg.find(g=>Math.abs(g.start.y-y)<1e-6)?.label||`Y${ny.indexOf(y)+1}`));const nodes=[...model.nodes];let i=nodes.length+1;for(const l of model.levels){if(gridAxis==="X"){for(const y of ny)if(!findNode(nodes,c,y,l.elevation))nodes.push({id:`N${i++}`,position:{x:c,y,z:l.elevation},levelId:l.id});}else{for(const x of nx)if(!findNode(nodes,x,c,l.elevation))nodes.push({id:`N${i++}`,position:{x,y:c,z:l.elevation},levelId:l.id});}}commit({...model,grids:makeGridLines(nx,ny,xl,yl),nodes},"Grid added.");setResetSignal(r=>r+1);}
  function addLevel(){const z=Number(levelElevation);if(!Number.isFinite(z)||model.levels.some(l=>Math.abs(l.elevation-z)<1e-6))return;const {xs,ys}=extractGrid(model.grids),id=`L${model.levels.length}`,level={id,name:levelName||`Level ${model.levels.length}`,elevation:z},nodes=[...model.nodes];let i=nodes.length+1;for(const y of ys)for(const x of xs)nodes.push({id:`N${i++}`,position:{x,y,z},levelId:id});commit({...model,levels:[...model.levels,level].sort((a,b)=>a.elevation-b.elevation),nodes},"Level added.");setResetSignal(r=>r+1);}
  function editGrid(axis:GridAxis,index:number,current:number){const raw=prompt(`New ${axis} spacing (m)`,current.toFixed(2));if(raw===null)return;const d=Number(raw);if(!Number.isFinite(d)||d<=0)return;const {xs,ys,xg,yg}=extractGrid(model.grids),coords=axis==="X"?xs:ys,threshold=coords[index+1],delta=d-current,shift=coords.map((v,i)=>i>index?v+delta:v),nodes=model.nodes.map(n=>({...n,position:{...n.position,...(axis==="X"&&n.position.x>=threshold-1e-6?{x:n.position.x+delta}:{}),...(axis==="Y"&&n.position.y>=threshold-1e-6?{y:n.position.y+delta}:{})}}));commit({...model,grids:makeGridLines(axis==="X"?shift:xs,axis==="Y"?shift:ys,xg.map(g=>g.label),yg.map(g=>g.label)),nodes},"Grid spacing updated.");}
  function editLevel(index:number,current:number){const ls=[...model.levels].sort((a,b)=>a.elevation-b.elevation),raw=prompt("New level height (m)",current.toFixed(2));if(raw===null)return;const d=Number(raw);if(!Number.isFinite(d)||d<=0)return;const delta=d-current,ids=new Set(ls.slice(index+1).map(l=>l.id));commit({...model,levels:model.levels.map(l=>ids.has(l.id)?{...l,elevation:l.elevation+delta}:l).sort((a,b)=>a.elevation-b.elevation),nodes:model.nodes.map(n=>n.levelId&&ids.has(n.levelId)?{...n,position:{...n.position,z:n.position.z+delta}}:n)},"Level spacing updated.");}
  function assignSection(sectionId:string){if(selected.length!==1||selected[0].type!=="member")return;const opt=sectionOptions.find(s=>s.id===sectionId);if(!opt)return;const section:Section={id:opt.id,family:opt.family||"W",materialType:"steel",designation:opt.designation_metric||opt.designation,geometry:{},properties:opt.properties};commit({...model,sections:model.sections.some(s=>s.id===section.id)?model.sections:[...model.sections,section],members:model.members.map(m=>m.id===selected[0].id?{...m,sectionId:section.id}:m)},"Section assigned.");}
  function saveProject(){const pkg:LtqPackage={format:"linkoteq-project",version:1,savedAt:new Date().toISOString(),model};const blob=new Blob([JSON.stringify(pkg,null,2)]),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${model.project.name.replace(/[^a-z0-9_-]+/gi,"-")}.ltq`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500);}
  async function openProject(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;try{const raw=JSON.parse(await f.text()) as LtqPackage|StructuralModel;const incoming=(raw as LtqPackage).format==="linkoteq-project"?(raw as LtqPackage).model:raw as StructuralModel;const m:StructuralModel={...incoming,schemaVersion:"0.2",loadSources:incoming.loadSources||[]};setModel(m);setPast([]);setFuture([]);setSelected([]);setSelectedNodes([]);setResetSignal(r=>r+1);}catch{setStatus("Invalid LTQ file.");}e.target.value="";}
  useEffect(()=>{const h=(e:KeyboardEvent)=>{const t=e.target as HTMLElement;if(["INPUT","SELECT","TEXTAREA"].includes(t?.tagName))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();}else if(mod&&e.key.toLowerCase()==="c"){e.preventDefault();copySelection();}else if(mod&&e.key.toLowerCase()==="v"){e.preventDefault();setStatus("Right-click a target node and choose Paste Here.");}else if(mod&&e.key.toLowerCase()==="s"){e.preventDefault();saveProject();}else if(e.key==="Delete"||e.key==="Backspace"){e.preventDefault();deleteSelection();}else if(e.key==="Enter"&&tool==="slab"&&selectedNodes.length>=3)finishSlab();};window.addEventListener("keydown",h);return()=>window.removeEventListener("keydown",h);},[model,past,future,selected,basePointId,clipboard,tool,selectedNodes]);
  const {xs,ys}=extractGrid(model.grids),levels=[...model.levels].sort((a,b)=>a.elevation-b.elevation),selectedMember=selected.length===1&&selected[0].type==="member"?model.members.find(m=>m.id===selected[0].id):undefined,selectedSurface=selected.length===1&&selected[0].type==="surface"?model.surfaces.find(s=>s.id===selected[0].id):undefined,selectedNode=selectedNodes.length===1?model.nodes.find(n=>n.id===selectedNodes[0]):undefined;
  return <div className="appShell" onPointerDown={()=>context&&setContext(null)}>
    <header className="topbar"><strong>Linkoteq 3D Structural Editor</strong><div className="topActions"><button onClick={()=>{setModel(createBaseModel());setSelected([]);setSelectedNodes([]);setResetSignal(r=>r+1);}}>New</button><button onClick={()=>projectInput.current?.click()}>Open</button><button onClick={saveProject}>Save</button><button onClick={undo} disabled={!past.length}>↶</button><button onClick={redo} disabled={!future.length}>↷</button><button onClick={deleteSelection}>⌫</button><button className="runButton">Run</button><button onClick={()=>window.print()}>Print</button><button>IFC</button></div><input ref={projectInput} hidden type="file" accept=".ltq,application/json" onChange={openProject}/></header>
    <div className="importbar"><button onClick={()=>aiInput.current?.click()}>PDF/Image → AI</button><button onClick={()=>dxfInput.current?.click()}>DXF</button><button onClick={()=>ifcInput.current?.click()}>IFC</button><input ref={aiInput} hidden type="file" accept=".pdf,image/*"/><input ref={dxfInput} hidden type="file" accept=".dxf"/><input ref={ifcInput} hidden type="file" accept=".ifc"/><span className="statusText">{status}</span></div>
    <main className="workspace"><aside className="toolbar"><section className="panelBlock"><h3>Model tools</h3><div className="toolGrid twoCol">{(["select","beam","column","brace","wall","slab"] as Tool[]).map(t=><button key={t} className={tool===t?"active":""} onClick={()=>{setTool(t);setSelectedNodes([]);}}>{t==="select"?"Select":`+ ${t[0].toUpperCase()}${t.slice(1)}`}</button>)}</div>{tool==="slab"&&selectedNodes.length>=3&&<button className="primaryWide" onClick={()=>finishSlab()}>Finish Slab ({selectedNodes.length})</button>}</section><section className="panelBlock"><h3>Add Grid</h3><div className="inlineFields"><select value={gridAxis} onChange={e=>setGridAxis(e.target.value as GridAxis)}><option>X</option><option>Y</option></select><input value={gridName} onChange={e=>setGridName(e.target.value)}/></div><div className="fieldWithUnit"><input value={gridCoordinate} onChange={e=>setGridCoordinate(e.target.value)}/><span>m</span></div><button className="primaryWide" onClick={addGrid}>Add Grid</button></section><section className="panelBlock"><h3>Add Level</h3><input value={levelName} onChange={e=>setLevelName(e.target.value)}/><div className="fieldWithUnit"><input value={levelElevation} onChange={e=>setLevelElevation(e.target.value)}/><span>m</span></div><button className="primaryWide" onClick={addLevel}>Add Level</button></section><section className="panelBlock"><h3>Selection</h3><div className="selectionText">{selected.length?`${selected.length} element(s)`:selectedNode?`Node ${selectedNode.id}`:"0 selected"}{basePointId?` · base ${basePointId}`:""}</div>{selected.length>0&&<button onClick={copySelection}>Copy</button>}</section></aside>
    <section className="viewport" onContextMenu={e=>e.preventDefault()} onPointerDown={e=>e.stopPropagation()}><Canvas shadows camera={{position:[18,12,18],fov:45}}><Scene model={model} selected={selected} selectedNodes={selectedNodes} onEntityClick={selectEntity} onEntityContext={(r,e)=>{selectEntity(r);setContext({x:e.nativeEvent.clientX,y:e.nativeEvent.clientY,kind:"entity",entity:r});}} onNodeClick={onNodeClick} onNodeContext={(n,e)=>{setSelected([]);setSelectedNodes([n.id]);setContext({x:e.nativeEvent.clientX,y:e.nativeEvent.clientY,kind:"node",nodeId:n.id});}} onGrid={editGrid} onLevel={editLevel} resetSignal={resetSignal}/></Canvas>{awaitingBase&&<div className="basePrompt">Multiple elements selected — click a blue node to set the copy base point.</div>}<div className="viewControls"><button onClick={()=>setResetSignal(r=>r+1)}>⌂</button></div><div className="mobileDimensions"><div><b>X</b>{xs.slice(0,-1).map((x,i)=><button key={i} onClick={()=>editGrid("X",i,xs[i+1]-x)}>{(xs[i+1]-x).toFixed(2)}m</button>)}</div><div><b>Y</b>{ys.slice(0,-1).map((y,i)=><button key={i} onClick={()=>editGrid("Y",i,ys[i+1]-y)}>{(ys[i+1]-y).toFixed(2)}m</button>)}</div><div><b>L</b>{levels.slice(0,-1).map((l,i)=><button key={i} onClick={()=>editLevel(i,levels[i+1].elevation-l.elevation)}>{(levels[i+1].elevation-l.elevation).toFixed(2)}m</button>)}</div></div></section>
    <aside className="inspector"><h2>Inspector</h2><p className="selectionText">{selected.length?`${selected.length} element(s) selected`:selectedNode?`Node ${selectedNode.id} selected`:"0 selected"}</p>{selectedMember&&<><h3>W Section</h3><select className="sectionSelect" value={selectedMember.sectionId||""} onChange={e=>assignSection(e.target.value)}><option value="">Select W-section…</option>{sectionOptions.map(s=><option key={s.id} value={s.id}>{s.designation_metric||s.designation}</option>)}</select></>}<h3>Loads</h3><LoadManager model={model} selectedSurface={selectedSurface} selectedMember={selectedMember} selectedNode={selectedNode} onModelChange={commit}/><details><summary>Core Model JSON</summary><pre>{JSON.stringify(model,null,2)}</pre></details></aside></main>
    {context&&<div className="contextMenu" style={{left:context.x,top:context.y}} onPointerDown={e=>e.stopPropagation()}>{context.kind==="node"?<><button onClick={()=>chooseBasePoint(model.nodes.find(n=>n.id===context.nodeId)!)}>Set as Base Point</button><button disabled={!clipboard} onClick={()=>pasteAt(model.nodes.find(n=>n.id===context.nodeId)!)}>Paste Here</button></>:<><button onClick={copySelection}>Copy</button><button onClick={()=>{setAwaitingBase(true);setContext(null);setStatus("Click a node to set base point.");}}>Set Base Point…</button><button className="contextDanger" onClick={deleteSelection}>Delete</button></>}</div>}
  </div>;
}
