import type { Load, LoadCase, LoadCombination, LoadSource, Material, Member, MemberLoadDirection, Section, StructuralModel, Support, UnitValue } from "@linkoteq/structural-core";

export const CORE_SCHEMA_VERSION = "0.5" as const;
export const LEGACY_SCHEMA_VERSION = "0.2" as const;
type R = Record<string, unknown>;
export type MigrationResult = { model: StructuralModel; warnings: string[] };

const rec=(v:unknown):R=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as R:{};
const arr=(v:unknown):unknown[]=>Array.isArray(v)?v:[];
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const text=(v:unknown,f:string):string=>{if(typeof v!=="string"||!v)throw new Error(`MISSING_${f.toUpperCase()}`);return v};
const finite=(v:unknown,f:string):number=>{if(typeof v!=="number"||!Number.isFinite(v))throw new Error(`MISSING_${f.toUpperCase()}`);return v};
const uv=(v:unknown,f:string):UnitValue=>{const x=rec(v);if(typeof x.value!=="number"||!Number.isFinite(x.value)||typeof x.unit!=="string"||!x.unit)throw new Error(`${f.toUpperCase()}_UNIT_VALUE_REQUIRED`);return{value:x.value,unit:x.unit}};
const ouv=(v:unknown,f:string):UnitValue|undefined=>v===undefined||v===null?undefined:uv(v,f);
const pick=(s:R,...ks:string[]):unknown=>{for(const k of ks)if(s[k]!==undefined)return s[k]};
const category=(v:unknown):LoadCase["category"]=>{const x=typeof v==="string"?v.toLowerCase():"",ok:LoadCase["category"][]=["dead","live","roof-live","snow","rain","wind","seismic","temperature","construction","other"];if(!ok.includes(x as LoadCase["category"]))throw new Error("UNSUPPORTED_LEGACY_LOAD_CATEGORY");return x as LoadCase["category"]};

function migrateMaterial(v:unknown,w:string[]):Material{
 const s=rec(v),p=rec(s.properties),a=rec(s.analysis),get=(...ks:string[])=>pick(a,...ks)??pick(p,...ks)??pick(s,...ks),id=text(s.id,"material_id"),t=s.type??p.type;
 if(!["steel","concrete","wood","other"].includes(String(t)))throw new Error("UNSUPPORTED_LEGACY_MATERIAL_TYPE");
 const out:Material={id,type:t as Material["type"],name:text(s.name??p.name,"material_name"),analysis:{E:uv(get("E","e","elasticModulus"),`material_${id}_E`),G:uv(get("G","g","shearModulus"),`material_${id}_G`),nu:finite(get("nu","poisson","poissonRatio"),`material_${id}_nu`),rho:uv(get("rho","density"),`material_${id}_rho`),fy:ouv(get("fy","Fy","yieldStrength"),`material_${id}_fy`)}};
 const known=new Set(["id","type","name","analysis","properties","E","e","elasticModulus","G","g","shearModulus","nu","poisson","poissonRatio","rho","density","fy","Fy","yieldStrength"]),extra=Object.fromEntries(Object.entries(s).filter(([k])=>!known.has(k)));
 if(Object.keys(extra).length){out.metadata={legacy:extra};w.push(`LEGACY_MATERIAL_METADATA_PRESERVED:${id}`)} return out
}
function migrateSection(v:unknown,w:string[]):Section{
 const s=rec(v),p=rec(s.properties),a=rec(s.analysis),get=(...ks:string[])=>pick(a,...ks)??pick(p,...ks)??pick(s,...ks),id=text(s.id,"section_id");
 const out:Section={id,family:text(s.family??p.family??"other","section_family"),designation:typeof s.designation==="string"?s.designation:undefined,analysis:{A:uv(get("A","area"),`section_${id}_A`),Iy:uv(get("Iy","iy"),`section_${id}_Iy`),Iz:uv(get("Iz","iz"),`section_${id}_Iz`),J:uv(get("J","j"),`section_${id}_J`)}};
 for(const k of ["Ay","Az","Sy","Sz","Zy","Zz","ry","rz"] as const){const x=get(k);if(x!==undefined)out.analysis[k]=uv(x,`section_${id}_${k}`)}
 const known=new Set(["id","family","designation","analysis","properties","A","area","Iy","iy","Iz","iz","J","j","Ay","Az","Sy","Sz","Zy","Zz","ry","rz"]),extra=Object.fromEntries(Object.entries(s).filter(([k])=>!known.has(k)));
 if(Object.keys(extra).length){out.metadata={legacy:extra};w.push(`LEGACY_SECTION_METADATA_PRESERVED:${id}`)} return out
}
const dofs=(v:unknown)=>{const r=rec(v);return{DX:Boolean(r.DX??r.ux),DY:Boolean(r.DY??r.uy),DZ:Boolean(r.DZ??r.uz),RX:Boolean(r.RX??r.rx),RY:Boolean(r.RY??r.ry),RZ:Boolean(r.RZ??r.rz)}};
function migrateSupport(v:unknown):Support{const s=rec(v);return{id:text(s.id,"support_id"),nodeId:text(s.nodeId,"support_node_id"),restraints:dofs(s.restraints)}}
const release=(v:unknown):Member["startRelease"]=>Object.keys(rec(v)).length?dofs(v):undefined;
function migrateMember(v:unknown):Member{const s=rec(v);return{...(s as unknown as Member),id:text(s.id,"member_id"),type:(s.type??"other") as Member["type"],startNodeId:text(s.startNodeId,"member_start_node_id"),endNodeId:text(s.endNodeId,"member_end_node_id"),materialId:text(s.materialId,"member_material_id"),sectionId:text(s.sectionId,"member_section_id"),startRelease:release(s.startRelease),endRelease:release(s.endRelease)}}
function migrateLoadSource(v:unknown):LoadSource{const s=rec(v),id=text(s.id,"load_source_id"),calc=s.calculator??s.source,allowed=["manual","snow","wind","seismic","self-weight","other"];return{id,category:category(s.category??s.loadCategory??"other"),name:text(s.name??calc??id,"load_source_name"),calculator:typeof calc==="string"&&allowed.includes(calc)?calc as LoadSource["calculator"]:"other",calculatorVersion:typeof s.calculatorVersion==="string"?s.calculatorVersion:undefined,codeEdition:typeof s.codeEdition==="string"?s.codeEdition:undefined,jurisdiction:typeof s.jurisdiction==="string"?s.jurisdiction:undefined,inputs:rec(s.inputs??s.inputProvenance),status:s.status==="generated"||s.status==="stale"||s.status==="error"||s.status==="manual"?s.status:calc==="manual"?"manual":"generated",generatedAt:typeof s.generatedAt==="string"?s.generatedAt:undefined}}
function migrateLoadCase(v:unknown):LoadCase{const s=rec(v);return{id:text(s.id,"load_case_id"),name:text(s.name??s.label??s.id,"load_case_name"),category:category(s.category??s.type),sourceId:typeof s.sourceId==="string"?s.sourceId:undefined,analysisType:s.analysisType==="response-spectrum"||s.analysisType==="other"?s.analysisType:"static",tags:Array.isArray(s.tags)?s.tags.filter((x):x is string=>typeof x==="string"):undefined}}
function provenance(s:R){const p=rec(s.provenance),sourceId=pick(p,"sourceId")??s.sourceId??s.loadSourceId,calculatorRunId=pick(p,"calculatorRunId")??s.calculatorRunId??s.runId,formulaRef=pick(p,"formulaRef")??s.formulaRef,note=pick(p,"note")??s.note;if(![sourceId,calculatorRunId,formulaRef,note].some(x=>typeof x==="string"))return;return{sourceId:typeof sourceId==="string"?sourceId:undefined,calculatorRunId:typeof calculatorRunId==="string"?calculatorRunId:undefined,formulaRef:typeof formulaRef==="string"?formulaRef:undefined,note:typeof note==="string"?note:undefined}}
function migrateLoad(v:unknown):Load{
 const s=rec(v),id=text(s.id,"load_id"),loadCaseId=text(s.loadCaseId,"load_case_id"),type=text(s.type,"load_type"),p=provenance(s);
 if(type==="nodal"){const c=rec(s.components),components:Record<string,UnitValue>={};for(const d of ["FX","FY","FZ","MX","MY","MZ"])if(c[d]!==undefined)components[d]=uv(c[d],`load_${id}_${d}`);if(!Object.keys(components).length)throw new Error(`UNSUPPORTED_LOSSY_LEGACY_LOAD:${id}`);return{id,type:"nodal",nodeId:text(s.nodeId??s.targetId,"load_target_id"),loadCaseId,coordinateSystem:"global",components,provenance:p}}
 if(type==="line"){const memberId=text(s.memberId??s.targetId,"load_target_id"),direction=text(s.direction,"load_direction") as MemberLoadDirection,coordinateSystem=s.coordinateSystem==="member-local"?"member-local":"global";
  if(s.x!==undefined&&s.magnitude!==undefined&&s.w1===undefined&&s.w2===undefined)return{id,type:"member-point",memberId,loadCaseId,coordinateSystem,direction,magnitude:uv(s.magnitude,`load_${id}_magnitude`),x:uv(s.x,`load_${id}_x`),provenance:p};
  if(s.w1!==undefined||s.w2!==undefined||s.distribution==="distributed")return{id,type:"member-distributed",memberId,loadCaseId,coordinateSystem,direction,w1:uv(s.w1??s.magnitude,`load_${id}_w1`),w2:uv(s.w2??s.w1??s.magnitude,`load_${id}_w2`),x1:ouv(s.x1,`load_${id}_x1`),x2:ouv(s.x2,`load_${id}_x2`),provenance:p};
  throw new Error(`AMBIGUOUS_LEGACY_LINE_LOAD:${id}`)
 }
 if(type==="area"){const surfaceId=text(s.surfaceId??s.targetId,"load_target_id");if(s.pressure===undefined)throw new Error(`AMBIGUOUS_LEGACY_AREA_LOAD:${id}`);return{id,type:"surface-pressure",surfaceId,loadCaseId,pressure:uv(s.pressure,`load_${id}_pressure`),convention:"surface-normal",provenance:p}}
 if(type==="self-weight")return{id,type:"self-weight",loadCaseId,globalDirection:text(s.globalDirection,"self_weight_direction") as "FX"|"FY"|"FZ",factor:finite(s.factor,"self_weight_factor"),targetMemberIds:Array.isArray(s.targetMemberIds)?s.targetMemberIds.map(x=>text(x,"self_weight_target_id")):undefined,provenance:p};
 if(["member-point","member-distributed","surface-pressure"].includes(type))throw new Error(`LEGACY_PROJECT_CONTAINS_V05_LOAD_TYPE:${id}`);
 throw new Error(`UNSUPPORTED_LOSSY_LEGACY_LOAD:${id}`)
}
function migrateCombination(v:unknown):LoadCombination{const s=rec(v),raw=rec(s.factors??s.loadCaseFactors),factors:Record<string,number>={};for(const[k,x]of Object.entries(raw))factors[k]=finite(x,`combination_factor_${k}`);if(!Object.keys(factors).length)throw new Error("LOAD_COMBINATION_FACTORS_REQUIRED");return{id:text(s.id,"load_combination_id"),name:text(s.name??s.label??s.id,"load_combination_name"),factors,limitState:(["ULS","SLS","ASD","other"] as const).includes(s.limitState as never)?s.limitState as LoadCombination["limitState"]:undefined,tags:Array.isArray(s.tags)?s.tags.filter((x):x is string=>typeof x==="string"):undefined,codeRef:typeof s.codeRef==="string"?s.codeRef:undefined}}
function unique(m:R){for(const k of ["nodes","materials","sections","members","supports","surfaces","loadSources","loadCases","loads","loadCombinations"]){const seen=new Set<string>();for(const x of arr(m[k])){const id=text(rec(x).id,`${k}_id`);if(seen.has(id))throw new Error(`DUPLICATE_STABLE_ID:${k}:${id}`);seen.add(id)}}}
function refs(m:StructuralModel){const ids=<T extends{id:string}>(x:T[])=>new Set(x.map(i=>i.id)),n=ids(m.nodes),ma=ids(m.materials),se=ids(m.sections),me=ids(m.members),su=ids(m.surfaces),so=ids(m.loadSources??[]),ca=ids(m.loadCases);
 for(const x of m.members){if(!n.has(x.startNodeId)||!n.has(x.endNodeId))throw new Error(`ORPHANED_MEMBER_NODE_REFERENCE:${x.id}`);if(!ma.has(x.materialId))throw new Error(`ORPHANED_MEMBER_MATERIAL_REFERENCE:${x.id}`);if(!se.has(x.sectionId))throw new Error(`ORPHANED_MEMBER_SECTION_REFERENCE:${x.id}`)}
 for(const x of m.supports)if(!n.has(x.nodeId))throw new Error(`ORPHANED_SUPPORT_NODE_REFERENCE:${x.id}`);
 for(const x of m.loadCases)if(x.sourceId&&!so.has(x.sourceId))throw new Error(`ORPHANED_LOAD_SOURCE_REFERENCE:${x.id}`);
 for(const x of m.loads){if(!ca.has(x.loadCaseId))throw new Error(`ORPHANED_LOAD_CASE_REFERENCE:${x.id}`);if(x.provenance?.sourceId&&!so.has(x.provenance.sourceId))throw new Error(`ORPHANED_LOAD_SOURCE_REFERENCE:${x.id}`);if(x.type==="nodal"&&!n.has(x.nodeId))throw new Error(`MISSING_LOAD_TARGET:${x.id}`);if((x.type==="member-point"||x.type==="member-distributed")&&!me.has(x.memberId))throw new Error(`MISSING_LOAD_TARGET:${x.id}`);if(x.type==="surface-pressure"&&!su.has(x.surfaceId))throw new Error(`MISSING_LOAD_TARGET:${x.id}`)}
 for(const x of m.loadCombinations)for(const k of Object.keys(x.factors))if(!ca.has(k))throw new Error(`ORPHANED_COMBINATION_LOAD_CASE:${x.id}:${k}`)
}
export function assertCanonicalV05(model:unknown):asserts model is StructuralModel{const m=rec(model);if(m.schemaVersion!==CORE_SCHEMA_VERSION)throw new Error("CORE_V05_REQUIRED");unique(m);for(const x of arr(m.materials)){const a=rec(rec(x).analysis);for(const k of ["id","type","name"])text(rec(x)[k],`material_${k}`);for(const k of ["E","G","rho"])uv(a[k],`material_${k}`);finite(a.nu,"material_nu")}for(const x of arr(m.sections)){const a=rec(rec(x).analysis);text(rec(x).id,"section_id");for(const k of ["A","Iy","Iz","J"])uv(a[k],`section_${k}`)}for(const x of arr(m.supports))if(Object.values(migrateSupport(x).restraints).length!==6)throw new Error("SUPPORT_SIX_DOF_REQUIRED");for(const x of arr(m.loads)){const q=rec(x),t=text(q.type,"load_type");text(q.id,"load_id");text(q.loadCaseId,"load_case_id");if(!["nodal","member-point","member-distributed","surface-pressure","self-weight","level","diaphragm"].includes(t))throw new Error(`UNSUPPORTED_CORE_LOAD:${t}`)}refs(m as unknown as StructuralModel)}
export function migrateProjectToV05(input:unknown):MigrationResult{const root=rec(input),s=root.format==="linkoteq-project"?rec(root.model):root,v=String(s.schemaVersion??"");if(v===CORE_SCHEMA_VERSION){const model=clone(s) as unknown as StructuralModel;assertCanonicalV05(model);return{model,warnings:[]}}if(v!==LEGACY_SCHEMA_VERSION)throw new Error(`UNSUPPORTED_CORE_SCHEMA:${v||"<missing>"}`);const warnings=["Project migrated from Core v0.2 to Core v0.5; newly saved projects use Core v0.5 only."],raw=clone(s),project=rec(raw.project),model={...raw,schemaVersion:CORE_SCHEMA_VERSION,project:{...project,metadata:{...rec(project.metadata),migrationFromSchema:LEGACY_SCHEMA_VERSION,migrationToSchema:CORE_SCHEMA_VERSION}},materials:arr(raw.materials).map(x=>migrateMaterial(x,warnings)),sections:arr(raw.sections).map(x=>migrateSection(x,warnings)),members:arr(raw.members).map(migrateMember),supports:arr(raw.supports).map(migrateSupport),loadSources:arr(raw.loadSources).map(migrateLoadSource),loadCases:arr(raw.loadCases).map(migrateLoadCase),loads:arr(raw.loads).map(migrateLoad),loadCombinations:arr(raw.loadCombinations).map(migrateCombination)} as unknown as StructuralModel;const normalized=clone(model) as StructuralModel;assertCanonicalV05(normalized);return{model:normalized,warnings}}
